# Generated by Django 2.2 on 2019-06-15 17:55

from django.db import migrations, models
import style_transfer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.ImageField(upload_to='Z:/style/style_transfer/media/images')),
            ],
        ),
        migrations.CreateModel(
            name='Uploadpics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contentfile', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=style_transfer.models.upload_location, width_field='width_field')),
                ('Stylefile', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=style_transfer.models.upload_location, width_field='width_field')),
                ('Doodlefile', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=style_transfer.models.upload_location, width_field='width_field')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
