# Generated by Django 2.2 on 2019-06-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='contentupload/', width_field='width_field'),
        ),
    ]
