# Generated by Django 2.2 on 2019-06-15 19:03

from django.db import migrations, models
import style_transfer.models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0002_auto_20190616_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='contentupload/'),
        ),
        migrations.AlterField(
            model_name='uploadpics',
            name='Contentfile',
            field=models.ImageField(blank=True, null=True, upload_to=style_transfer.models.upload_location),
        ),
        migrations.AlterField(
            model_name='uploadpics',
            name='Doodlefile',
            field=models.ImageField(blank=True, null=True, upload_to=style_transfer.models.upload_location),
        ),
        migrations.AlterField(
            model_name='uploadpics',
            name='Stylefile',
            field=models.ImageField(blank=True, null=True, upload_to=style_transfer.models.upload_location),
        ),
    ]
