# Generated by Django 2.2 on 2019-06-16 07:24

from django.db import migrations, models
import style_transfer.models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0003_auto_20190616_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Style_num', models.IntegerField(default=1)),
                ('Stylefile', models.ImageField(blank=True, null=True, upload_to=style_transfer.models.upload_location)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='uploadpics',
            name='Stylefile',
        ),
        migrations.AddField(
            model_name='uploadpics',
            name='Style_num',
            field=models.IntegerField(default=1),
        ),
    ]
