# Generated by Django 2.2 on 2019-06-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0004_auto_20190616_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadpics',
            name='Doodlefile',
        ),
        migrations.AddField(
            model_name='uploadpics',
            name='Url_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
